site_name: OnbonBX Docs
site_url: https://www.onbonbx.com/
site_description: Documentations of OnbonBX products
site_author: Kudriavtsev Dmytro
copyright: Copyright &copy; <a href="https://github.com/Kudriavtsev-Dmytro" rel="Kudriavtsev Dmytro">Kudriavtsev Dmytro</a>


theme:
  language: en
  #logo: assets/images/logo.svg
  #favicon: assets/images/favicon.ico
  highlightjs: true
  
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  #  - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
     
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: red
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: red
   
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    #https://materialdesignicons.com/
    - icon: material/github
      link: https://github.com/Kudriavtsev-Dmytro
      name: GitHub Kudriavtsev Dmytro    
    - icon: material/web
      link: https://www.onbonbx.com/
      name: OnbonBX website

  
  #generator: false

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: Like
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: Dislike
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

#extra_css:
  #- stylesheets/extra.css

#extra_javascript:
  #- javascripts/shortcuts.js

markdown_extensions:
  - toc:
      permalink: "#"
      separator: "_"
  - attr_list
  - admonition
  - def_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret  
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true 

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

  - table-reader

  - i18n:
      docs_structure: folder
      material_alternate: true
      default_language: en
      languages:
        en:
          name: English
          build: true
          site_name: "OnbonBX documentation"
        zh:
          name: 中文
          build: true
          site_name: "OnbonBX 文档"
        uk:
          name: Українська
          #build: true
          site_name: "OnbonBX документація"
        ru_UK:
          name: Русский
          #build: true
          site_name: "OnbonBX документация"
      
      nav_translations:
        en:
          1Specifications: Specifications
          2Manuals: Manuals
        zh:
          1Specifications: 规格
          2Manuals: 用户手册
        uk:
          1Specifications: Характеристики
          2Manuals: Посібники
        ru_UK:
          1Specifications: Спецификации
          2Manuals: Руководства
