site_name: 'Manual'
docs_dir: '../../docs/cn'                           # Where to find the English markdown files
site_dir: '../../generated/cn'                      # Where to put the English HTML files

theme:
    name: material
    #custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
    #logo: assets/images/logo.svg                    # The logo is shared by all languages
    #favicon: assets/images/favicon.ico              # The favicon is shared by all languages
    language: cn                                    # The build's language

extra:                                              # Language Selection
  alternate:  

      # Switch to English
    - name: English
      link: /en/
      lang: en

    # Switch to Chinese
    - name: Chinese
      link: /cn/
      lang: cn

    # Switch to Ukrainian
    - name: Ukrainian
      link: /ua/
      lang: ua

plugins:
  - search:                                         
      lang: cn                                      # Set language for search

nav:
- Welcome: index.md